export default {
  SET_LOADER: 'SET_LOADER',
  SET_NOTES_LIST: 'SET_NOTES_LIST',
  SET_SELECTED_NOTE: 'SET_SELECTED_NOTE',
  ADD_NOTE:'ADD_NOTE',
  UPDATE_NOTE: 'UPDATE_NOTE',
  DELETE_NOTE: 'DELETE_NOTE',
};
